### ISSUE TITLE
Documentation "fix"

### ISSUE THREAD

**Issue by maurymarkowitz** [MJ10/Yet-Another-Programming-Language#1]
This borders on insanity, I realize, but could you change the readme.md from "This is a basic interpreter..." to "This is a simple interpreter..."?

This is not a BASIC interpreter, but try telling Google and GitHub that.

**Comment by MJ10** [comment]
Apologies for the confusion, fixed in this [commit](https://github.com/MJ10/Yet-Another-Programming-Language/commit/4f215643276a4b4bcc10e95c2bfa64be4ffcbc59)
